# 2020/7/30 ~ version 1.1
# This is the Keras framework.
# You can change the way you train by changing this file.

#######################################################################################
# TRAINING CONFIG....                                                                 #
#######################################################################################
# Set the details of the data to be learned
Resourcedata  :
  # How to read a data set(README reference)
  # input : text, onefolder, folder, bclearning(text)
  readdata    : text
  resourcepath: ./dataset.txt
  # Image size setting
  img_row     : 227
  img_col     : 227
  # Class type (described in sequence)
  classes     :
    - choki
    - goo
    - paa

# Validation data setting.
Validation    :
  # Use validation data?
  isUse         : true
  # batch size
  batchsize   : 16
  # How to read a data set(README reference)
  # input : text, onefolder, folder
  readdata    : folder
  resourcepath: ./dataset/

# Set the number of trainings, learning rate, etc.
Trainsetting  :
  epoch       : 10
  batchsize   : 16
  learnrate   : 0.001
  shuffle     : true
  ##############################################################
  # use imagedatagenerator function
  useAugment  : false
  # featurewise_center(bool)
  featurewise_center : true
  # samplewise_center(bool)
  samplewise_center  : true
  # featurewise_std_normalization(bool)
  featurewise_std_normalization : true
  # samplewise_std_normalization(bool)
  samplewise_std_normalization : true
  # zca_whitening(bool)
  zca_whitening  : false
  # rotation_range(int value, 0=>dont use)
  rotation_range : 0
  # width_shift_range(float, 0.0 => dont use)
  width_shift_range : 0.3
  # height_shift_range(float, 0.0 => dont use)
  height_shift_range : 0.3
  # horizontal_flip(bool)
  horizontal_flip : false
  # vertical_flip(bool)
  vertical_flip : false
  # shear_range (float, 0.0 => dont use)
  shear_range : 0.0
  ##############################################################
  isBClearning : false
  isMixup      : true

# Setting up a learning model
Modelsetting  :
  # load model? (True  => load model(h5 or json file. and pls set retrain?
  #              False => Create model. mymodel.py load model)
  isLoad      : true
  # categorical_crossentropy or mean_squared_error
  # binary_crossentropy or kullback_leibler_divergence.
  model_loss  : categorical_crossentropy
  # adam or sgd or adagrad or adadelta.
  optimizers  : adam
  # Relearning a trained model
  retrain_model   : true
  # json file or h5 file
  model_path  : ./result/08_01_00_15/model/test_10.h5
  # h5 weihgt file.
  weight_path : ./result/08_01_00_15/model/testend_model_weight.h5
  # To learn or not to learn(default : true)
  trainable   : true

Trainingresult :
  # Set the name of the model to save
  model_name  : test
  # Do you want to draw a graph of your results after training?
  # (The resulting graph will be saved.)
  graph_write : false

# callback function setting.
callback      :
  # Setting the target of monitoring(Alternative loss or val_loss)
  monitor     : loss
  verbose     : 1
  # True => Save from judgment result, False => Save every period.
  save_best_only : true
  # True = model weights save, False = model save.
  save_weights_only : false
  # Selecting the maximum or minimum value (max => acc,val_acc, min => loss, val_loss)
  mode        : min
  # How many epochs do we run callbacks on?
  period      : 10
  # Set the directory of tensorboard.
  tensorboard : ./
  # Number of epochs of tensorboard updates
  tb_epoch    : 1

#######################################################################################
# TEST CONFIG....                                                                     #
#######################################################################################
# target model setting.
TESTModel     :
  path        : ./result/07_29_13_21/
  model_path  : model/model_architecture.yaml
  weight_path : model/test_10.h5

# test dataset setting
testresourcedata :
  # How to read a data set(README reference)
  # input : text, onefolder, folder
  readdata : text
  resourcepath : ./dataset.txt