# 2020/4/10 ~ version 0.1
# This is the Keras framework.
# You can change the way you train by changing this file.

# execution environment setting
running       :
  GPU         : false
  # To learn or not to learn
  trainable   : false

# Set the details of the data to be learned
Resorsedata   :
  # How to read data(text , folder, name)
  readdata : text
  # Image size setting
  img_row     : 227
  img_col     : 227
  # Number of image classes
  num_classes : 2
  # Class type (described in sequence)
  classes     :
    - 1
    - 2
  
# Set the number of trainings, learning rate, etc.
Trainsetting  :
  epoch       : 10
  batchsize   : 32
  learnrate   : 0.01

# Setting up a learning model
Modelsetting  :
  # 
  model_loss  : categorical_crossentropy
  # 
  optimizers  : adam
  #
  network_architecture : "nin"
  # Relearning a trained model
  use_model   : false
  model_path  : path


Trainingresult :
  # Set the name of the model to save
  model_name  : "test"
  # Do you want to draw a graph of your results after training?
  # (The resulting graph will be saved.)
  graph_write : false
  # Set the path to be saved.(retrieved from the current directory)
  path        : "/"

# callback function setting.
callback      :
  # Setting the target of monitoring(Alternative loss or val_loss)
  moniter     : "val_loss"
  verbose     : 1
  save_best_only : true
  save_weights_only : false
  # Selecting the maximum or minimum value
  mode : "min"
  # How many epochs do we run callbacks on?
  period : 5
  # Set the directory of tensorboard.
  tensorboard : path
  # Number of epochs of tensorboard updates
  tb_epoch : 1